/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.an.view;
import javax.swing.Timer;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import com.an.bean.DanhMucBean;
import com.an.controller.ChuyenManHinhController;
import com.an.controller.DangNhapController;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;


/**
 *
 * @author ngoca
 */
public class MainJFrame extends javax.swing.JFrame {

	/**
	 * Creates new form MainJFrame
	 */
	public MainJFrame() {
		initComponents();
		
	

        // Không cho phép thay đổi kích thước cửa sổ
   
        // Định nghĩa các thành phần giao diện và thêm chúng vào cửa sổ ở đây

        // Đảm bảo ứng dụng kết thúc khi đóng cửa sổ
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		
		setTitle("Demo1");
			
			ChuyenManHinhController controller = new ChuyenManHinhController(jpnView);
			controller.setView(jpnDangNhap, jlbDangNhap);

			List<DanhMucBean> listItem = new ArrayList<>();
			listItem.add(new DanhMucBean("DangNhap", jpnDangNhap, jlbDangNhap));
			listItem.add(new DanhMucBean("TrangChu", jpnTrangChu, jlbTrangChu));
			listItem.add(new DanhMucBean("HoaDon", jpnHoaDon, jlbHoaDon));
			listItem.add(new DanhMucBean("CanHo", jpnCanHo, jlbCanHo));
			listItem.add(new DanhMucBean("NhanVien", jpnNhanVien, jlbNhanVien));
			listItem.add(new DanhMucBean("HoTro", jpnHoTro, jlbHoTro));
			listItem.add(new DanhMucBean("CaiDat", jpnCaiDat, jlbCaiDat));
			listItem.add(new DanhMucBean("Xe", jpnQuanLiXe, jlbXe));
		
			
			controller.setEvent(listItem);
			
			
			

	}
	
	
  
	
	/*
	width: 210px
	height: 600px
	*/
	int width = 146;
	int height = 600;
		//phương thức mở menu
	void openMenuBar() {
    int newX = jpnView.getX() + (width); // Vị trí mới của jpnView sau khi mở menu
    int newY = jpnView.getY();
    jpnView.setLocation(newX, newY); // Di chuyển jpnView đến vị trí mới
    jpnView.repaint();
    
    // Tạo luồng chạy song song với luồng chính Main
    new Thread(new Runnable() {
        @Override
        public void run() {
            for (int i = 0; i < width; i++) {
                jpnMenu.setSize(i + 42, height); // Thêm 42 vào kích thước menu
                pnMenu2.setSize(i + 42, 42); // Thêm 42 vào kích thước pnMenu2
            }
        }
    }).start();
}

	
	
	void closeMenuBar(){
		
		int newX = jpnView.getX() - width; // Vị trí mới của jpnView sau khi đóng menu
		int newY = jpnView.getY();

		jpnView.setLocation(newX, newY); // Di chuyển jpnView đến vị trí mới
		jpnView.repaint();
		//tạo luồng chạy song song với luồng chính Main
		new Thread(new Runnable(){
			@Override
			public void run(){//phương thức cụm menu lại
				for(int i = width; i>0 ;i--){
					jpnMenu.setSize(43, height);
					pnMenu2.setSize(i, height);
				}
		}
	
		}).start();
	}
	

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jpnMain = new javax.swing.JPanel();
                menu = new javax.swing.JPanel();
                jLabel10 = new javax.swing.JLabel();
                jpnView = new javax.swing.JPanel();
                pnMenu2 = new javax.swing.JPanel();
                close = new javax.swing.JLabel();
                jpnMenu = new javax.swing.JPanel();
                jpnQuanLiXe = new javax.swing.JPanel();
                jlbXe = new javax.swing.JLabel();
                jpnTrangChu = new javax.swing.JPanel();
                jlbTrangChu = new javax.swing.JLabel();
                jpnCanHo = new javax.swing.JPanel();
                jlbCanHo = new javax.swing.JLabel();
                jpnHoaDon = new javax.swing.JPanel();
                jlbHoaDon = new javax.swing.JLabel();
                jpnNhanVien = new javax.swing.JPanel();
                jlbNhanVien = new javax.swing.JLabel();
                jpnHoTro = new javax.swing.JPanel();
                jlbHoTro = new javax.swing.JLabel();
                jpnCaiDat = new javax.swing.JPanel();
                jlbCaiDat = new javax.swing.JLabel();
                jpnDangNhap = new javax.swing.JPanel();
                jlbDangNhap = new javax.swing.JLabel();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                jpnMain.setBackground(new java.awt.Color(204, 204, 255));
                jpnMain.setPreferredSize(new java.awt.Dimension(900, 596));

                menu.setBackground(new java.awt.Color(204, 204, 255));

                jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/an/anh/Menu_1.png"))); // NOI18N
                jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                jLabel10MouseClicked(evt);
                        }
                });

                javax.swing.GroupLayout menuLayout = new javax.swing.GroupLayout(menu);
                menu.setLayout(menuLayout);
                menuLayout.setHorizontalGroup(
                        menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
                );
                menuLayout.setVerticalGroup(
                        menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(menuLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );

                jpnView.setBackground(new java.awt.Color(204, 255, 255));
                jpnView.setPreferredSize(new java.awt.Dimension(625, 471));
                jpnView.setVerifyInputWhenFocusTarget(false);

                javax.swing.GroupLayout jpnViewLayout = new javax.swing.GroupLayout(jpnView);
                jpnView.setLayout(jpnViewLayout);
                jpnViewLayout.setHorizontalGroup(
                        jpnViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 847, Short.MAX_VALUE)
                );
                jpnViewLayout.setVerticalGroup(
                        jpnViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
                );

                pnMenu2.setBackground(new java.awt.Color(204, 204, 255));
                pnMenu2.setVerifyInputWhenFocusTarget(false);

                close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/an/anh/Menu_1.png"))); // NOI18N
                close.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                closeMouseClicked(evt);
                        }
                });

                javax.swing.GroupLayout pnMenu2Layout = new javax.swing.GroupLayout(pnMenu2);
                pnMenu2.setLayout(pnMenu2Layout);
                pnMenu2Layout.setHorizontalGroup(
                        pnMenu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnMenu2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(close, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );
                pnMenu2Layout.setVerticalGroup(
                        pnMenu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnMenu2Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(close)
                                .addContainerGap())
                );

                jpnMenu.setBackground(new java.awt.Color(204, 204, 255));
                jpnMenu.setPreferredSize(new java.awt.Dimension(190, 60));

                jpnQuanLiXe.setBackground(new java.awt.Color(204, 204, 255));

                jlbXe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/an/anh/Car.png"))); // NOI18N
                jlbXe.setText("    Quản lí xe");

                javax.swing.GroupLayout jpnQuanLiXeLayout = new javax.swing.GroupLayout(jpnQuanLiXe);
                jpnQuanLiXe.setLayout(jpnQuanLiXeLayout);
                jpnQuanLiXeLayout.setHorizontalGroup(
                        jpnQuanLiXeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jpnQuanLiXeLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jlbXe, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );
                jpnQuanLiXeLayout.setVerticalGroup(
                        jpnQuanLiXeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnQuanLiXeLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jlbXe, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                );

                jpnTrangChu.setBackground(new java.awt.Color(204, 204, 255));

                jlbTrangChu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/an/anh/Home.png"))); // NOI18N
                jlbTrangChu.setText("    Trang chủ");

                javax.swing.GroupLayout jpnTrangChuLayout = new javax.swing.GroupLayout(jpnTrangChu);
                jpnTrangChu.setLayout(jpnTrangChuLayout);
                jpnTrangChuLayout.setHorizontalGroup(
                        jpnTrangChuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jpnTrangChuLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jlbTrangChu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
                );
                jpnTrangChuLayout.setVerticalGroup(
                        jpnTrangChuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jlbTrangChu, javax.swing.GroupLayout.Alignment.TRAILING)
                );

                jpnCanHo.setBackground(new java.awt.Color(204, 204, 255));

                jlbCanHo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/an/anh/Room.png"))); // NOI18N
                jlbCanHo.setText("   Căn hộ");

                javax.swing.GroupLayout jpnCanHoLayout = new javax.swing.GroupLayout(jpnCanHo);
                jpnCanHo.setLayout(jpnCanHoLayout);
                jpnCanHoLayout.setHorizontalGroup(
                        jpnCanHoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jpnCanHoLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jlbCanHo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
                );
                jpnCanHoLayout.setVerticalGroup(
                        jpnCanHoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jpnCanHoLayout.createSequentialGroup()
                                .addComponent(jlbCanHo)
                                .addGap(0, 0, Short.MAX_VALUE))
                );

                jpnHoaDon.setBackground(new java.awt.Color(204, 204, 255));

                jlbHoaDon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/an/anh/Bill.png"))); // NOI18N
                jlbHoaDon.setText("   Hóa Đơn");

                javax.swing.GroupLayout jpnHoaDonLayout = new javax.swing.GroupLayout(jpnHoaDon);
                jpnHoaDon.setLayout(jpnHoaDonLayout);
                jpnHoaDonLayout.setHorizontalGroup(
                        jpnHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jpnHoaDonLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jlbHoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );
                jpnHoaDonLayout.setVerticalGroup(
                        jpnHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jlbHoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                );

                jpnNhanVien.setBackground(new java.awt.Color(204, 204, 255));

                jlbNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/an/anh/Staff.png"))); // NOI18N
                jlbNhanVien.setText("    Quản lí nhân viên");

                javax.swing.GroupLayout jpnNhanVienLayout = new javax.swing.GroupLayout(jpnNhanVien);
                jpnNhanVien.setLayout(jpnNhanVienLayout);
                jpnNhanVienLayout.setHorizontalGroup(
                        jpnNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jpnNhanVienLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jlbNhanVien)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );
                jpnNhanVienLayout.setVerticalGroup(
                        jpnNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jpnNhanVienLayout.createSequentialGroup()
                                .addComponent(jlbNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                );

                jpnHoTro.setBackground(new java.awt.Color(204, 204, 255));

                jlbHoTro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/an/anh/Technical Support.png"))); // NOI18N
                jlbHoTro.setText("    Chăm sóc khách hàng");

                javax.swing.GroupLayout jpnHoTroLayout = new javax.swing.GroupLayout(jpnHoTro);
                jpnHoTro.setLayout(jpnHoTroLayout);
                jpnHoTroLayout.setHorizontalGroup(
                        jpnHoTroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jpnHoTroLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jlbHoTro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(13, 13, 13))
                );
                jpnHoTroLayout.setVerticalGroup(
                        jpnHoTroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnHoTroLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jlbHoTro))
                );

                jpnCaiDat.setBackground(new java.awt.Color(204, 204, 255));

                jlbCaiDat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/an/anh/Settings.png"))); // NOI18N
                jlbCaiDat.setText("   Cài đặt");

                javax.swing.GroupLayout jpnCaiDatLayout = new javax.swing.GroupLayout(jpnCaiDat);
                jpnCaiDat.setLayout(jpnCaiDatLayout);
                jpnCaiDatLayout.setHorizontalGroup(
                        jpnCaiDatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jlbCaiDat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                );
                jpnCaiDatLayout.setVerticalGroup(
                        jpnCaiDatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jlbCaiDat, javax.swing.GroupLayout.Alignment.TRAILING)
                );

                jpnDangNhap.setBackground(new java.awt.Color(204, 204, 255));

                jlbDangNhap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/an/anh/User.png"))); // NOI18N
                jlbDangNhap.setText("   Trung tâm người dùng");
                jlbDangNhap.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                jlbDangNhapMouseClicked(evt);
                        }
                });

                javax.swing.GroupLayout jpnDangNhapLayout = new javax.swing.GroupLayout(jpnDangNhap);
                jpnDangNhap.setLayout(jpnDangNhapLayout);
                jpnDangNhapLayout.setHorizontalGroup(
                        jpnDangNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jlbDangNhap, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                );
                jpnDangNhapLayout.setVerticalGroup(
                        jpnDangNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jlbDangNhap)
                );

                javax.swing.GroupLayout jpnMenuLayout = new javax.swing.GroupLayout(jpnMenu);
                jpnMenu.setLayout(jpnMenuLayout);
                jpnMenuLayout.setHorizontalGroup(
                        jpnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jpnTrangChu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jpnCanHo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jpnHoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jpnHoTro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jpnNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jpnMenuLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jpnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jpnCaiDat, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                        .addComponent(jpnDangNhap, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(jpnQuanLiXe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                );
                jpnMenuLayout.setVerticalGroup(
                        jpnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jpnMenuLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jpnTrangChu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jpnCanHo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jpnHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jpnQuanLiXe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jpnNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jpnHoTro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jpnDangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)
                                .addComponent(jpnCaiDat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10))
                );

                javax.swing.GroupLayout jpnMainLayout = new javax.swing.GroupLayout(jpnMain);
                jpnMain.setLayout(jpnMainLayout);
                jpnMainLayout.setHorizontalGroup(
                        jpnMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jpnMainLayout.createSequentialGroup()
                                .addGroup(jpnMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jpnMainLayout.createSequentialGroup()
                                                .addComponent(pnMenu2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(2, 2, 2)
                                                .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jpnMainLayout.createSequentialGroup()
                                                .addGap(2, 2, 2)
                                                .addComponent(jpnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, 0)))
                                .addComponent(jpnView, javax.swing.GroupLayout.DEFAULT_SIZE, 847, Short.MAX_VALUE)
                                .addContainerGap())
                );
                jpnMainLayout.setVerticalGroup(
                        jpnMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jpnView, javax.swing.GroupLayout.DEFAULT_SIZE, 602, Short.MAX_VALUE)
                        .addGroup(jpnMainLayout.createSequentialGroup()
                                .addGroup(jpnMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(pnMenu2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 0, 0)
                                .addComponent(jpnMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 554, Short.MAX_VALUE)
                                .addContainerGap())
                );

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jpnMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jpnMain, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 602, Short.MAX_VALUE)
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void jlbDangNhapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbDangNhapMouseClicked
                // TODO add your handling code here:

        }//GEN-LAST:event_jlbDangNhapMouseClicked

        private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
                // TODO add your handling code here:
                openMenuBar();
        }//GEN-LAST:event_jLabel10MouseClicked

        private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
                // TODO add your handling code here:
                closeMenuBar();
        }//GEN-LAST:event_closeMouseClicked

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
    DangNhapJDialog dialog = new DangNhapJDialog(null, true);
    dialog.setTitle("Đăng nhập hệ thống");
    dialog.setResizable(false);
    dialog.setLocationRelativeTo(null);
    dialog.setVisible(true); // Hiển thị cửa sổ đăng nhập
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		
	}

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JLabel close;
        private javax.swing.JLabel jLabel10;
        private javax.swing.JLabel jlbCaiDat;
        private javax.swing.JLabel jlbCanHo;
        private javax.swing.JLabel jlbDangNhap;
        private javax.swing.JLabel jlbHoTro;
        private javax.swing.JLabel jlbHoaDon;
        private javax.swing.JLabel jlbNhanVien;
        private javax.swing.JLabel jlbTrangChu;
        private javax.swing.JLabel jlbXe;
        private javax.swing.JPanel jpnCaiDat;
        private javax.swing.JPanel jpnCanHo;
        private javax.swing.JPanel jpnDangNhap;
        private javax.swing.JPanel jpnHoTro;
        private javax.swing.JPanel jpnHoaDon;
        private javax.swing.JPanel jpnMain;
        private javax.swing.JPanel jpnMenu;
        private javax.swing.JPanel jpnNhanVien;
        private javax.swing.JPanel jpnQuanLiXe;
        private javax.swing.JPanel jpnTrangChu;
        private javax.swing.JPanel jpnView;
        private javax.swing.JPanel menu;
        private javax.swing.JPanel pnMenu2;
        // End of variables declaration//GEN-END:variables


private static class ListItem {

		private static void add(DanhMucBean danhMucBean) {
		}

		public ListItem() {
		}
	}



}
